"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { requireRole } from "@/lib/auth/server";
import { createClient } from "@/lib/supabase/server";
import { appointmentSchema } from "./validation";

export type AppointmentActionState = { error?: string; message?: string };
const value = (data: FormData, name: string) => String(data.get(name) ?? "");
const status = (value: string) => value as "scheduled" | "checked_in" | "in_progress" | "completed" | "cancelled" | "no_show";
function input(data: FormData) { return { customerId:value(data,"customerId"), vehicleId:value(data,"vehicleId"), technicianId:value(data,"technicianId"), startsAt:new Date(value(data,"startsAt")).toISOString(), endsAt:new Date(value(data,"endsAt")).toISOString(), notes:value(data,"notes"), serviceIds:data.getAll("serviceIds").map(String), revision:value(data,"revision"), overrideConflict:value(data,"overrideConflict") || undefined }; }
function args(parsed: ReturnType<typeof appointmentSchema.parse>) { return { target_customer_id:parsed.customerId,target_vehicle_id:parsed.vehicleId,target_technician_id:parsed.technicianId,target_starts_at:parsed.startsAt,target_ends_at:parsed.endsAt,target_notes:parsed.notes,selected_services:parsed.serviceIds.map((serviceId) => ({ serviceId })),allow_conflict:parsed.overrideConflict === "true" }; }
export async function saveAppointment(_: AppointmentActionState, formData: FormData): Promise<AppointmentActionState> { const staff=await requireRole(["admin","front_desk"]); const parsed=appointmentSchema.safeParse(input(formData)); if(!parsed.success)return {error:parsed.error.issues[0]?.message}; if(parsed.data.overrideConflict && staff.role!=="admin")return {error:"Only an administrator can override a technician conflict."}; const appointmentId=value(formData,"appointmentId")||null; const {data,error}=await (await createClient()).rpc("save_appointment",{target_appointment_id:appointmentId,expected_revision:parsed.data.revision ?? null,...args(parsed.data)}); if(error)return {error:"Appointment could not be saved. Check for technician conflicts or refresh the calendar."}; if(!appointmentId)redirect(`/appointments/${data}`); revalidatePath("/appointments");revalidatePath(`/appointments/${appointmentId}`);return {message:"Appointment saved."}; }
export async function rescheduleAppointment(id:string, startsAt:string, endsAt:string, revision:number) { await requireRole(["admin","front_desk"]); const {error}=await (await createClient()).rpc("reschedule_appointment",{target_appointment_id:id,target_starts_at:startsAt,target_ends_at:endsAt,expected_revision:revision,allow_conflict:false}); if(error)return {error:"Reschedule was not saved. The technician may be busy or this appointment changed."};revalidatePath("/appointments");return {message:"Appointment rescheduled."}; }
export async function transitionAppointment(formData:FormData) { await requireRole(["admin","front_desk"]); const id=value(formData,"appointmentId"); await (await createClient()).rpc("transition_appointment",{target_appointment_id:id,next_status:status(value(formData,"nextStatus")),expected_revision:Number(value(formData,"revision"))});revalidatePath("/appointments");revalidatePath(`/appointments/${id}`); }
export async function convertAppointment(formData:FormData) { await requireRole(["admin","front_desk"]); const id=value(formData,"appointmentId");const {data,error}=await (await createClient()).rpc("convert_appointment_to_work_order",{target_appointment_id:id,expected_revision:Number(value(formData,"revision"))});if(!error&&data)redirect(`/work-orders/${data}`); }
