/* eslint-disable @typescript-eslint/no-explicit-any -- nested Supabase relations are unknown until types are regenerated after reset. */
import Link from "next/link";
import { addDays, format, startOfWeek } from "date-fns";
import { PageHeader } from "@/components/operational";
import { AppointmentCalendar } from "@/features/appointments/appointment-calendar";
import { AppointmentForm } from "@/features/appointments/appointment-form";
import { requireRole } from "@/lib/auth/server";
import { createClient } from "@/lib/supabase/server";
export default async function AppointmentsPage({searchParams}:{searchParams:Promise<{date?:string;create?:string}>}) {const staff=await requireRole(["admin","front_desk"]);const params=await searchParams;const selected=params.date?new Date(`${params.date}T00:00:00`):new Date();const start=startOfWeek(selected,{weekStartsOn:6});const end=addDays(start,7);const supabase=await createClient();const [{data:rows},{data:customers},{data:vehicles},{data:services},{data:technicians}]=await Promise.all([supabase.from("appointments").select("id,requested_service_summary,starts_at,ends_at,status,revision,customers(full_name),vehicles(plate_number)").gte("starts_at",start.toISOString()).lt("starts_at",end.toISOString()).order("starts_at"),supabase.from("customers").select("id,full_name,phone").is("archived_at",null).order("full_name"),supabase.from("vehicles").select("id,customer_id,plate_number,make,model").is("archived_at",null),supabase.from("service_catalog").select("id,name").is("archived_at",null).order("name"),supabase.from("profiles").select("id,display_name").eq("role","technician").eq("account_status","active").order("display_name")]);const events=(rows??[]).map((row:any)=>({id:row.id,title:`${row.customers?.full_name??"Customer"} · ${row.vehicles?.plate_number??row.requested_service_summary}`,start:row.starts_at,end:row.ends_at,status:row.status,revision:row.revision}));return <section className="space-y-8"><PageHeader eyebrow="Scheduling" title="Appointments" description="Week calendar in Asia/Kabul time. Drag an appointment or open it to edit precise times." actions={<Link className="rounded-md bg-brand-primary px-4 py-2 text-sm font-medium text-brand-primary-foreground" href={`/appointments?date=${format(selected,"yyyy-MM-dd")}&create=1`}>New appointment</Link>}/><form className="flex items-center gap-2 rounded-lg border bg-card p-3"><label className="text-sm font-medium">Calendar date <input className="ml-2 h-9 rounded-md border bg-background px-2" defaultValue={format(selected,"yyyy-MM-dd")} name="date" type="date"/></label><button className="rounded-md border px-3 py-2 text-sm font-medium">Go</button><Link className="text-sm font-medium underline" href="/appointments">Current day</Link></form>{params.create==="1"?<AppointmentForm admin={staff.role==="admin"} customers={(customers??[]).map((item)=>({id:item.id,name:item.full_name,phone:item.phone}))} vehicles={(vehicles??[]).map((item)=>({id:item.id,customerId:item.customer_id,label:[item.make,item.model].filter(Boolean).join(" ")||"Vehicle",plate:item.plate_number}))} services={(services??[]).map((item)=>({id:item.id,name:item.name}))} technicians={(technicians??[]).map((item)=>({id:item.id,name:item.display_name}))}/>:null}<AppointmentCalendar date={format(selected,"yyyy-MM-dd")} events={events}/></section>}
