/* eslint-disable @typescript-eslint/no-explicit-any -- Supabase table types are regenerated after local reset. */
import { CurrencyDisplay, EmptyState, PageHeader, StatusBadge } from "@/components/operational";
import { correctInventoryForm, restockPartForm } from "@/features/inventory/actions";
import { PartForm } from "@/features/inventory/part-form";
import { requireRole } from "@/lib/auth/server";
import { createClient } from "@/lib/supabase/server";
const pageSize = 25;
export default async function InventoryPage({ searchParams }: { searchParams: Promise<{ q?: string; category?: string; status?: string; low?: string; page?: string; create?: string }> }) {
  const staff = await requireRole(["admin", "front_desk"]); const filters = await searchParams; const supabase = await createClient(); const page = Math.max(1, Number(filters.page) || 1);
  let request = supabase.from("parts").select("id,name,sku,category,unit,quantity_on_hand,reorder_threshold,sell_price_minor,archived_at", { count: "exact" }).order("name").range((page - 1) * pageSize, page * pageSize - 1);
  if (filters.q) request = request.or(`name.ilike.%${filters.q}%,sku.ilike.%${filters.q}%`); if (filters.category) request = request.eq("category", filters.category); if (filters.status === "active") request = request.is("archived_at", null); if (filters.status === "archived") request = request.not("archived_at", "is", null); if (filters.low === "true") request = request.filter("quantity_on_hand", "lte", "reorder_threshold");
  const { data, count, error } = await request; const parts = (data ?? []) as any[]; const pageCount = Math.max(1, Math.ceil((count ?? 0) / pageSize));
  return <section className="space-y-8"><PageHeader eyebrow="Inventory" title="Parts and supplies" description="Stock changes are immutable movements. Low stock means on-hand quantity is at or below its threshold." />
    {filters.create === "1" ? <PartForm admin={staff.role === "admin"} /> : <a className="inline-flex rounded-md bg-brand-primary px-4 py-2 text-sm font-medium text-brand-primary-foreground" href="/inventory?create=1">Add part</a>}
    <form className="grid gap-2 rounded-lg border bg-card p-3 md:grid-cols-[1fr_auto_auto_auto_auto]"><input className="h-10 rounded-md border bg-background px-3" defaultValue={filters.q ?? ""} name="q" placeholder="Search name or SKU" /><input className="h-10 rounded-md border bg-background px-3" defaultValue={filters.category ?? ""} name="category" placeholder="Category" /><select className="h-10 rounded-md border bg-background px-3" defaultValue={filters.status ?? "active"} name="status"><option value="active">Active</option><option value="archived">Archived</option><option value="">All statuses</option></select><label className="flex items-center gap-2 text-sm"><input defaultChecked={filters.low === "true"} name="low" type="checkbox" value="true" />Low stock</label><button className="rounded-md border px-4 text-sm font-medium">Filter</button></form>
    {error ? <p className="text-destructive">Inventory could not be loaded.</p> : parts.length ? <div className="overflow-x-auto rounded-lg border bg-card"><table className="w-full text-left text-sm"><thead><tr className="border-b text-muted-foreground"><th className="p-3">Part</th><th className="p-3">Stock</th><th className="p-3">Threshold</th><th className="p-3">Selling price</th><th className="p-3">Status</th></tr></thead><tbody>{parts.map((part) => <tr className="border-b last:border-0" key={part.id as string}><td className="p-3"><p className="font-medium">{part.name as string}</p><p className="text-xs text-muted-foreground">{(part.sku as string) || "No SKU"}{part.category ? ` · ${String(part.category)}` : ""}</p></td><td className="p-3">{String(part.quantity_on_hand)} {String(part.unit)}<form action={restockPartForm} className="mt-2 flex gap-1"><input name="partId" type="hidden" value={part.id as string}/><input className="h-7 w-16 rounded border px-1" min="0.001" name="quantity" placeholder="Qty" required step="0.001" type="number"/><input className="h-7 w-24 rounded border px-1" name="reason" placeholder="Restock note"/><button className="text-xs font-medium underline">Restock</button></form>{staff.role === "admin" ? <form action={correctInventoryForm} className="mt-1 flex gap-1"><input name="partId" type="hidden" value={part.id as string}/><input className="h-7 w-16 rounded border px-1" name="quantity" placeholder="±Qty" required step="0.001" type="number"/><input className="h-7 w-24 rounded border px-1" name="reason" placeholder="Correction reason" required/><button className="text-xs font-medium text-destructive underline">Correct</button></form> : null}</td><td className="p-3">{String(part.reorder_threshold)} {String(part.unit)}</td><td className="p-3"><CurrencyDisplay amount={Number(part.sell_price_minor)} /></td><td className="p-3">{part.archived_at ? <StatusBadge status="inactive"/> : Number(part.quantity_on_hand) <= Number(part.reorder_threshold) ? <StatusBadge status="pending"/> : <StatusBadge status="active"/>}</td></tr>)}</tbody></table></div> : <EmptyState title="No parts found" description="Add a part or adjust the inventory filters."/>}<p className="text-sm text-muted-foreground">Page {page} of {pageCount}</p></section>;
}
