"use server";
import { revalidatePath } from "next/cache";
import { requireRole,requireStaff } from "@/lib/auth/server";
import { createClient } from "@/lib/supabase/server";
import { partSchema } from "./validation";
export type InventoryActionState={error?:string;message?:string};const value=(data:FormData,name:string)=>String(data.get(name)??"");
export async function savePart(_:InventoryActionState,formData:FormData):Promise<InventoryActionState>{const staff=await requireRole(["admin","front_desk"]);const id=value(formData,"partId");const parsed=partSchema.safeParse({name:value(formData,"name"),sku:value(formData,"sku"),category:value(formData,"category"),unit:value(formData,"unit"),quantity:id?"0":value(formData,"quantity"),threshold:value(formData,"threshold"),cost:value(formData,"cost"),selling:value(formData,"selling")});if(!parsed.success)return{error:parsed.error.issues[0]?.message};if(parsed.data.cost!==null&&staff.role!=="admin")return{error:"Only administrators can set cost information."};const payload={name:parsed.data.name,sku:parsed.data.sku,category:parsed.data.category,unit:parsed.data.unit,reorder_threshold:parsed.data.threshold,sell_price_minor:parsed.data.selling,...(staff.role==="admin"?{cost_price_minor:parsed.data.cost}: {})};const db=await createClient();const {error}=id?await db.from("parts").update(payload).eq("id",id):await db.rpc("create_part",{part_name:parsed.data.name,part_sku:parsed.data.sku??"",part_category:parsed.data.category,part_unit:parsed.data.unit,opening_quantity:parsed.data.quantity,threshold:parsed.data.threshold,cost_minor:staff.role==="admin"?(parsed.data.cost??null):null,selling_minor:parsed.data.selling});if(error)return{error:"Part could not be saved. SKU values must be unique."};revalidatePath("/inventory");return{message:id?"Part updated.":"Part created with an initial stock movement."};}
export async function restockPart(_:InventoryActionState,formData:FormData):Promise<InventoryActionState>{await requireRole(["admin","front_desk"]);const {error}=await(await createClient()).rpc("restock_part",{target_part_id:value(formData,"partId"),quantity:Number(value(formData,"quantity")),reason:value(formData,"reason")||null});if(error)return{error:"Restock could not be recorded."};revalidatePath("/inventory");return{message:"Restock recorded."};}
export async function restockPartForm(formData:FormData){await restockPart({},formData);}
export async function correctInventory(_:InventoryActionState,formData:FormData):Promise<InventoryActionState>{await requireRole(["admin"]);const {error}=await(await createClient()).rpc("correct_inventory",{target_part_id:value(formData,"partId"),quantity_delta:Number(value(formData,"quantity")),reason:value(formData,"reason")});if(error)return{error:"Correction could not be recorded."};revalidatePath("/inventory");return{message:"Correction recorded."};}
export async function correctInventoryForm(formData:FormData){await correctInventory({},formData);}
export async function setPartArchived(formData:FormData){const actor=await requireRole(["admin","front_desk"]);const archived=value(formData,"archived")==="true";await(await createClient()).from("parts").update({archived_at:archived?new Date().toISOString():null,archived_by:archived?actor.id:null}).eq("id",value(formData,"partId"));revalidatePath("/inventory");}
export async function usePart(_:InventoryActionState,formData:FormData):Promise<InventoryActionState>{await requireStaff();const workOrderId=value(formData,"workOrderId");const {error}=await(await createClient()).rpc("confirm_work_order_part_usage",{target_work_order_id:workOrderId,target_part_id:value(formData,"partId"),quantity:Number(value(formData,"quantity"))});if(error)return{error:"Part use could not be confirmed. Check stock or duplicate usage."};revalidatePath(`/work-orders/${workOrderId}`);revalidatePath("/inventory");return{message:"Part use confirmed and stock deducted."};}
export async function reversePartUse(formData:FormData){const staff=await requireStaff();const workOrderId=value(formData,"workOrderId");await(await createClient()).rpc("reverse_work_order_part_usage",{target_work_order_part_id:value(formData,"partLineId"),reason:value(formData,"reason")});revalidatePath(`/work-orders/${workOrderId}`);revalidatePath("/inventory");if(staff.role!=="technician")revalidatePath("/work-orders");}
